# Generated by Django 6.1.1 on 2026-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(max_length=500)),
                ('owner', models.CharField(max_length=255)),
                ('repo_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('license_name', models.CharField(blank=True, max_length=150, null=True)),
                ('repo_last_updated', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('checks', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('recent_commit_count', models.IntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Repository analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
